spring:
    application:
        name: rool
#    redis:
#      host: localhost
#      port: 6379
#      pool:
#        max-active: 8
#        max-wait: 1
#        max-idle: 8
#        min-idle: 0
#      timeout: 20000
server:
  port: 8002